apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app
  name: app
spec:
  containers:
    - name: app
      image: demo-registry:5000/demo-app
      env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://localhost:5432/demo"
        - name: SPRING_DATASOURCE_USERNAME
          value: demo
        - name: SPRING_DATASOURCE_PASSWORD
          value: Passw0rd
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: org.postgresql.Driver
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: org.hibernate.dialect.PostgreSQLDialect
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
    - name: postgres
      image: postgres:15
      env:
        - name: POSTGRES_USER
          value: demo
        - name: POSTGRES_PASSWORD
          value: Passw0rd
        - name: POSTGRES_DB
          value: demo
        - name: PGDATA
          value: /data/postgres
      ports:
        - containerPort: 5432
          name: tcp
          protocol: TCP
#  volumes:
#    - emptyDir: {}
#      name: app-data
