apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app
  name: app
spec:
  containers:
    - name: app
      image: demo-registry:5000/demo-app
      env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:h2:file:/app/data/todos"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      volumeMounts:
        - mountPath: /app/data
          name: app-data
  volumes:
    - emptyDir: {}
      name: app-data
